name = "quaternionicComputing"
version = "0.1.0"
keywords = ["math", "quaternion", "quantum-computing", "formalization"]
defaultTargets = ["QuaternionicComputing"]

[leanOptions]
pp.unicode.fun = true
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true
weak.linter.style.header = false
maxSynthPendingDepth = 3

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.31.0"

[[lean_lib]]
name = "QuaternionicComputing"
