module

public import QuaternionicComputing

/-!
# Axiom audit

This module grows with the public theorem surface.  Building it prints the
axioms used by each main exported result.
-/

#print axioms QuaternionicComputing.Quaternion.eq_complexPart_add_jPart_mul_j
#print axioms QuaternionicComputing.Quaternion.components_injective
#print axioms QuaternionicComputing.Quaternion.complexPart_mul
#print axioms QuaternionicComputing.Quaternion.jPart_mul
#print axioms QuaternionicComputing.Quaternion.complexPart_star
#print axioms QuaternionicComputing.Quaternion.jPart_star
#print axioms QuaternionicComputing.Quaternion.normSq_eq_complexPart_add_jPart
#print axioms QuaternionicComputing.Quaternion.phaseWitnessGate_normSq
#print axioms QuaternionicComputing.Quaternion.not_leftPhaseEquivalent_gate_i_input
#print axioms QuaternionicComputing.Quaternion.rightPhaseEquivalent_equivalence
#print axioms QuaternionicComputing.Quaternion.rightPhaseEquivalent_gate

#print axioms QuaternionicComputing.Matrix.realify_injective
#print axioms QuaternionicComputing.Matrix.realify_mul
#print axioms QuaternionicComputing.Matrix.realify_conjTranspose
#print axioms QuaternionicComputing.Matrix.realify_mulVec
#print axioms QuaternionicComputing.Matrix.realify_map_ofReal
#print axioms QuaternionicComputing.Matrix.realifyUnitaryEquivImage
#print axioms QuaternionicComputing.Matrix.realify_mem_orthogonal
#print axioms QuaternionicComputing.Matrix.realify_det
#print axioms QuaternionicComputing.Matrix.realify_mem_specialOrthogonal

#print axioms QuaternionicComputing.Quaternion.complexify_injective
#print axioms QuaternionicComputing.Quaternion.complexify_mul
#print axioms QuaternionicComputing.Quaternion.complexify_conjTranspose
#print axioms QuaternionicComputing.Quaternion.complexify_mul_complexificationJ
#print axioms QuaternionicComputing.Quaternion.complexifyUnitaryEquivImage
#print axioms QuaternionicComputing.Quaternion.complexify_mem_unitary
#print axioms QuaternionicComputing.Quaternion.complexify_mem_symplectic
#print axioms QuaternionicComputing.Quaternion.complexify_det_star_fixed
#print axioms QuaternionicComputing.Quaternion.complexify_det_eq_one_or_neg_one_of_mem_unitary

#print axioms QuaternionicComputing.State.Quaterbit.normalization
#print axioms QuaternionicComputing.State.quaternionBasisWeight_right_smul_of_normSq_eq_one
#print axioms QuaternionicComputing.State.QuaternionState.rightPhaseEquivalent_rightPhase
#print axioms QuaternionicComputing.State.rightPhaseEquivalent_quaternionBasisWeight
#print axioms QuaternionicComputing.State.rightPhaseEquivalent_quaternionTotalWeight
#print axioms QuaternionicComputing.State.quaternion_mulVec_right_smul
#print axioms QuaternionicComputing.State.rightPhaseEquivalent_mulVec

#print axioms QuaternionicComputing.State.realColumn0_injective
#print axioms QuaternionicComputing.State.realColumn1_injective
#print axioms QuaternionicComputing.State.realify_mulVec_realColumn0
#print axioms QuaternionicComputing.State.realify_mulVec_realColumn1
#print axioms QuaternionicComputing.State.realColumns_orthogonal
#print axioms QuaternionicComputing.State.realColumn0_bottomWeight
#print axioms QuaternionicComputing.State.realTopCombination_bottomWeight_of_rebit
#print axioms QuaternionicComputing.State.reducedRealOuter_realColumns
#print axioms QuaternionicComputing.State.reducedRealOuter_diagonal

#print axioms QuaternionicComputing.State.complexColumn0_injective
#print axioms QuaternionicComputing.State.complexColumn1_injective
#print axioms QuaternionicComputing.State.complexify_mulVec_complexColumn0
#print axioms QuaternionicComputing.State.complexify_mulVec_complexColumn1
#print axioms QuaternionicComputing.State.complexColumns_orthogonal
#print axioms QuaternionicComputing.State.complexColumn0_bottomWeight
#print axioms QuaternionicComputing.State.complexColumn1_bottomWeight
#print axioms QuaternionicComputing.State.complexTopCombination_bottomWeight_of_qubit

#print axioms QuaternionicComputing.Circuit.kronecker_one_mul
#print axioms QuaternionicComputing.Circuit.place_mul
#print axioms QuaternionicComputing.Circuit.place_mem_unitary
#print axioms QuaternionicComputing.Circuit.supportSplit
#print axioms QuaternionicComputing.Circuit.PlacedGate.denote_mem_unitary
#print axioms QuaternionicComputing.Circuit.OrderedCircuit.eval_append
#print axioms QuaternionicComputing.Circuit.OrderedCircuit.eval_map_of_denote_eq
#print axioms QuaternionicComputing.Circuit.OrderedCircuit.eval_mem_unitary
#print axioms QuaternionicComputing.Circuit.OrderSanity.eval_i_then_j_entry
#print axioms QuaternionicComputing.Circuit.OrderSanity.eval_j_then_i_entry

#print axioms QuaternionicComputing.Circuit.wireRealify_place
#print axioms QuaternionicComputing.Circuit.realifyPlacedGate_denote
#print axioms QuaternionicComputing.Circuit.localArity_realifyPlacedGate
#print axioms QuaternionicComputing.Circuit.isLocallyUnitary_realifyPlacedGate

#print axioms QuaternionicComputing.Circuit.wireComplexify_place
#print axioms QuaternionicComputing.Circuit.complexifyPlacedGate_denote
#print axioms QuaternionicComputing.Circuit.localArity_complexifyPlacedGate
#print axioms QuaternionicComputing.Circuit.isLocallyUnitary_complexifyPlacedGate

#print axioms QuaternionicComputing.State.star_dotProduct_mulVec_of_mem_unitary
#print axioms QuaternionicComputing.State.complexTotalWeight_mulVec_of_mem_unitary
#print axioms QuaternionicComputing.State.quaternionTotalWeight_mulVec_of_mem_unitary
#print axioms QuaternionicComputing.State.RealState.evolveUnitary
#print axioms QuaternionicComputing.State.ComplexState.evolveUnitary
#print axioms QuaternionicComputing.State.QuaternionState.evolveUnitary

#print axioms QuaternionicComputing.Circuit.card_addedWire
#print axioms QuaternionicComputing.Circuit.OrderedCircuit.maxLocalArity_le_iff
#print axioms QuaternionicComputing.Circuit.OrderedCircuit.mem_map_arity_provenance
#print axioms QuaternionicComputing.Circuit.OrderedCircuit.maxLocalArity_map_eq_add_one_of_nonempty

#print axioms QuaternionicComputing.Simulation.reindex_mulVec_transportAddedColumn
#print axioms QuaternionicComputing.Simulation.totalWeight_transportAddedColumn
#print axioms QuaternionicComputing.Simulation.sum_addedWireBottomWeight
#print axioms QuaternionicComputing.Simulation.sum_addedWireBottomWeight_normalized

#print axioms QuaternionicComputing.Simulation.eval_realifyCircuit
#print axioms QuaternionicComputing.Simulation.mem_realifyCircuit_arity
#print axioms QuaternionicComputing.Simulation.maxLocalArity_realifyCircuit_of_nonempty
#print axioms QuaternionicComputing.Simulation.eval_realifyCircuit_mulVec_wireRealTopCombination
#print axioms QuaternionicComputing.Simulation.realifyCircuitOutput_bottomProbability
#print axioms QuaternionicComputing.Simulation.complexToReal_exactSimulation

#print axioms QuaternionicComputing.Simulation.eval_complexifyCircuit
#print axioms QuaternionicComputing.Simulation.mem_complexifyCircuit_arity
#print axioms QuaternionicComputing.Simulation.maxLocalArity_complexifyCircuit_of_nonempty
#print axioms
  QuaternionicComputing.Simulation.eval_complexifyCircuit_mulVec_wireComplexTopCombination
#print axioms QuaternionicComputing.Simulation.complexifyCircuitOutput_bottomProbability
#print axioms QuaternionicComputing.Simulation.quaternionToComplex_exactSimulation

#print axioms QuaternionicComputing.Simulation.eval_quaternionToRealCircuit
#print axioms QuaternionicComputing.Simulation.mem_quaternionToRealCircuit_arity
#print axioms QuaternionicComputing.Simulation.quaternionToRealCircuitOutput_nestedEncoding_apply
#print axioms QuaternionicComputing.Simulation.quaternionToRealCircuitOutput_bottomProbability
#print axioms QuaternionicComputing.Simulation.quaternionToReal_exactSimulation

#print axioms QuaternionicComputing.Simulation.Examples.realifyComplexICircuit_true_amplitude
#print axioms QuaternionicComputing.Simulation.Examples.complexifyQuaternionJCircuit_true_amplitude

#print axioms QuaternionicComputing.Matrix.kronecker_mul_kronecker_of_entrywiseCommute
#print axioms QuaternionicComputing.Matrix.disjoint_kronecker_factors_commute_of_entrywiseCommute
#print axioms QuaternionicComputing.Matrix.QuaternionExamples.oneByOne_interchange_without_zeroOne
#print axioms QuaternionicComputing.Matrix.QuaternionExamples.oneByOne_interchange_i_j_failure

#print axioms QuaternionicComputing.Circuit.LegalSchedule.length_order
#print axioms QuaternionicComputing.Circuit.LegalSchedule.index_lt_index_of_precedes
#print axioms QuaternionicComputing.Circuit.LegalSchedule.scheduledCircuit_perm
#print axioms QuaternionicComputing.Circuit.LegalSchedule.scheduledEval_eq_of_pairwise_commute

#print axioms QuaternionicComputing.Simulation.eval_complexify_scheduledCircuit
#print axioms
  QuaternionicComputing.Simulation.eval_complexify_scheduledCircuit_ne_of_scheduledEval_ne
#print axioms QuaternionicComputing.Simulation.scheduledQuaternionToComplex_exactSimulation

#print axioms QuaternionicComputing.Circuit.OrderingWitness.iMixer_unitary
#print axioms QuaternionicComputing.Circuit.OrderingWitness.jMixer_unitary
#print axioms QuaternionicComputing.Circuit.OrderingWitness.gate_supports_disjoint
#print axioms QuaternionicComputing.Circuit.OrderingWitness.inputColumn_normalization
#print axioms QuaternionicComputing.Circuit.OrderingWitness.scheduled_operators_ne
#print axioms QuaternionicComputing.Circuit.OrderingWitness.iThenJOutput_basis00_weight
#print axioms QuaternionicComputing.Circuit.OrderingWitness.jThenIOutput_basis00_weight
#print axioms QuaternionicComputing.Circuit.OrderingWitness.output_basis00_weight_ne

#print axioms QuaternionicComputing.Simulation.OrderingWitness.complexified_scheduled_operators_ne
#print axioms QuaternionicComputing.Simulation.OrderingWitness.iThenJComplexOutput_basis00_weight
#print axioms QuaternionicComputing.Simulation.OrderingWitness.jThenIComplexOutput_basis00_weight
#print axioms QuaternionicComputing.Simulation.OrderingWitness.complexOutput_basis00_weight_ne

#print axioms QuaternionicComputing.Circuit.SupportLayering.depth_le_gateCount
#print axioms QuaternionicComputing.Circuit.SupportLayering.depth_eq_gateCount_of_commonWire

#print axioms QuaternionicComputing.Circuit.PlacedGate.denseEntrySlots_eq_four_pow
#print axioms
  QuaternionicComputing.Circuit.PlacedGate.localArity_le_log_four_of_denseEntrySlots_le
#print axioms QuaternionicComputing.Circuit.OrderedCircuit.translationWork_le_gateCount_mul
#print axioms
  QuaternionicComputing.Circuit.OrderedCircuit.totalDenseEntrySlots_map_eq_four_mul
#print axioms
  QuaternionicComputing.Circuit.OrderedCircuit.totalDenseEntrySlots_map_eq_sixteen_mul

#print axioms QuaternionicComputing.Circuit.ExactGateCompiler.primitive_of_mem_compileCircuit
#print axioms QuaternionicComputing.Circuit.ExactGateCompiler.arityBound_compileCircuit
#print axioms QuaternionicComputing.Circuit.ExactGateCompiler.eval_compileCircuit
#print axioms QuaternionicComputing.Circuit.ExactGateCompiler.gateCount_compileCircuit_le

#print axioms QuaternionicComputing.Circuit.length_allChronologicalOrders
#print axioms
  QuaternionicComputing.Circuit.mem_allChronologicalOrders_iff_exists_emptyLegalSchedule
#print axioms
  QuaternionicComputing.Circuit.LegalSchedule.order_mem_allChronologicalOrders
#print axioms QuaternionicComputing.Circuit.ScheduleCount.BoolChain.order_eq_schedule
#print axioms QuaternionicComputing.Circuit.ScheduleCount.BoolChain.reverseOrder_not_legal

#print axioms QuaternionicComputing.State.FiniteDistribution.eventWeight_eq_of_weight_eq
#print axioms QuaternionicComputing.State.FiniteDistribution.sum_pushforward_weight
#print axioms QuaternionicComputing.State.FiniteDistribution.pushforward_eq_of_weight_eq

#print axioms QuaternionicComputing.Semantics.ExactOperatorEq.mul
#print axioms QuaternionicComputing.Semantics.ExactCircuitEq.of_gatewise
#print axioms QuaternionicComputing.Semantics.ExactCircuitEq.append
#print axioms QuaternionicComputing.Semantics.OutputWeightEqAt.of_exact
#print axioms QuaternionicComputing.Semantics.BasisMeasurementEq.of_exact
#print axioms QuaternionicComputing.Semantics.PureInputBasisMeasurementEq.of_exact
#print axioms
  QuaternionicComputing.Semantics.basisMeasurementEq_iff_outputWeightEqAt_basis
#print axioms QuaternionicComputing.Semantics.outputWeightEqAt_basis_iff_column_weight
#print axioms
  QuaternionicComputing.Semantics.PureInputBasisMeasurementEq.basisMeasurementEq
#print axioms
  QuaternionicComputing.Semantics.basisWeightEq_iff_normalizedDistributionEq
#print axioms QuaternionicComputing.Semantics.BasisWeightEq.eventWeight_eq
#print axioms QuaternionicComputing.Semantics.BasisWeightEq.pushforward_eq
#print axioms QuaternionicComputing.Semantics.ExactCircuitEq.outputWeightEqAt
#print axioms QuaternionicComputing.Semantics.ExactCircuitEq.basisMeasurementEq
#print axioms QuaternionicComputing.Semantics.ExactCircuitEq.pureInputBasisMeasurementEq

#print axioms QuaternionicComputing.Real.signEquivalent_iff_eq_or_eq_neg
#print axioms QuaternionicComputing.State.RealState.rightSign_basisWeight
#print axioms QuaternionicComputing.State.signEquivalent_real_mulVec
#print axioms QuaternionicComputing.Semantics.ExactStateEq.normalizedDistributionEq
#print axioms QuaternionicComputing.Semantics.RealStatePhaseEq.equivalence
#print axioms QuaternionicComputing.Semantics.RealStatePhaseEq.normalizedDistributionEq
#print axioms QuaternionicComputing.Semantics.RealStatePhaseEq.raw_eval
#print axioms QuaternionicComputing.Semantics.RealStatePhaseEq.evolveUnitary
#print axioms QuaternionicComputing.Semantics.ComplexStatePhaseEq.equivalence
#print axioms QuaternionicComputing.Semantics.ComplexStatePhaseEq.normalizedDistributionEq
#print axioms QuaternionicComputing.Semantics.ComplexStatePhaseEq.raw_eval
#print axioms QuaternionicComputing.Semantics.ComplexStatePhaseEq.evolveUnitary
#print axioms QuaternionicComputing.Semantics.QuaternionStatePhaseEq.equivalence
#print axioms
  QuaternionicComputing.Semantics.QuaternionStatePhaseEq.normalizedDistributionEq
#print axioms QuaternionicComputing.Semantics.QuaternionStatePhaseEq.raw_eval
#print axioms QuaternionicComputing.Semantics.QuaternionStatePhaseEq.evolveUnitary

#print axioms QuaternionicComputing.State.RealRay.mk_eq_mk_iff
#print axioms QuaternionicComputing.State.RealRay.mk_eq_mk_iff_eq_or_eq_neg
#print axioms QuaternionicComputing.State.ComplexRay.mk_eq_mk_iff
#print axioms QuaternionicComputing.State.QuaternionRay.mk_eq_mk_iff
#print axioms QuaternionicComputing.State.QuaternionRay.function_ext
#print axioms QuaternionicComputing.State.realRay_nonempty_iff
#print axioms QuaternionicComputing.State.complexRay_nonempty_iff
#print axioms QuaternionicComputing.State.quaternionRay_nonempty_iff

#print axioms QuaternionicComputing.State.FiniteDistribution.pushforward_comp
#print axioms QuaternionicComputing.Circuit.OrderedCircuit.IsLocallyUnitary.append
#print axioms QuaternionicComputing.State.RealRay.distribution_mk
#print axioms QuaternionicComputing.State.ComplexRay.distribution_mk
#print axioms QuaternionicComputing.State.QuaternionRay.distribution_mk
#print axioms QuaternionicComputing.State.RealRay.evolveUnitary_comp
#print axioms QuaternionicComputing.State.ComplexRay.evolveUnitary_comp
#print axioms QuaternionicComputing.State.QuaternionRay.evolveUnitary_comp
#print axioms QuaternionicComputing.State.RealRay.evolveCircuit_append
#print axioms QuaternionicComputing.State.ComplexRay.evolveCircuit_append
#print axioms QuaternionicComputing.State.QuaternionRay.evolveCircuit_append
#print axioms QuaternionicComputing.Semantics.RealStatePhaseEq.iff_realRay_mk_eq
#print axioms QuaternionicComputing.Semantics.ComplexStatePhaseEq.iff_complexRay_mk_eq
#print axioms
  QuaternionicComputing.Semantics.QuaternionStatePhaseEq.iff_quaternionRay_mk_eq

#print axioms QuaternionicComputing.State.realSectorAction_comp_right
#print axioms
  QuaternionicComputing.State.realSectorAction_realTotalWeight_of_normSq_eq_one
#print axioms QuaternionicComputing.State.RealState.sectorRotation_comp_right
#print axioms
  QuaternionicComputing.State.realColumn0State_rightPhase_eq_realTopState
#print axioms
  QuaternionicComputing.State.realSectorPhaseEquivalent_equivalence
#print axioms
  QuaternionicComputing.State.realSectorPhaseEquivalent_iff_decode_rightPhaseEquivalent
#print axioms QuaternionicComputing.State.RealSectorOrbit.mk_eq_mk_iff
#print axioms QuaternionicComputing.State.RealSectorOrbit.function_ext
#print axioms QuaternionicComputing.State.realColumn0StateEquiv
#print axioms
  QuaternionicComputing.State.ComplexRay.realificationOrbit_mk_eq_realColumn1State
#print axioms QuaternionicComputing.State.complexRayEquivRealSectorOrbit
#print axioms
  QuaternionicComputing.State.ComplexRay.realificationOrbit_bijective
#print axioms
  QuaternionicComputing.State.ComplexRay.realificationOrbit_mk_eq_realTopState
#print axioms
  QuaternionicComputing.State.RealSectorOrbit.bottomDistribution_mk
#print axioms
  QuaternionicComputing.State.ComplexRay.realificationOrbit_distribution
#print axioms
  QuaternionicComputing.State.realColumn0State_rightPhase_realRay_eq_iff
#print axioms
  QuaternionicComputing.State.realColumn1State_rightPhase_realRay_eq_iff
#print axioms
  QuaternionicComputing.State.complexRay_realColumn0_lift_exists_iff_isEmpty
#print axioms
  QuaternionicComputing.State.complexRay_realColumn1_lift_exists_iff_isEmpty

#print axioms QuaternionicComputing.Semantics.RealGlobalSignEq.equivalence
#print axioms QuaternionicComputing.Semantics.ComplexGlobalPhaseEq.equivalence
#print axioms QuaternionicComputing.Semantics.RealInputBasisSignEq.equivalence
#print axioms QuaternionicComputing.Semantics.ComplexInputBasisPhaseEq.equivalence
#print axioms QuaternionicComputing.Semantics.RealOutputBasisSignEq.equivalence
#print axioms QuaternionicComputing.Semantics.ComplexOutputBasisPhaseEq.equivalence
#print axioms QuaternionicComputing.Semantics.RealProjectiveActionEq.equivalence
#print axioms QuaternionicComputing.Semantics.ComplexProjectiveActionEq.equivalence

#print axioms QuaternionicComputing.Semantics.RealGlobalSignEq.inputBasisSignEq
#print axioms QuaternionicComputing.Semantics.RealGlobalSignEq.outputBasisSignEq
#print axioms QuaternionicComputing.Semantics.RealGlobalSignEq.projectiveActionEq
#print axioms QuaternionicComputing.Semantics.ComplexGlobalPhaseEq.inputBasisPhaseEq
#print axioms QuaternionicComputing.Semantics.ComplexGlobalPhaseEq.outputBasisPhaseEq
#print axioms QuaternionicComputing.Semantics.ComplexGlobalPhaseEq.projectiveActionEq
#print axioms QuaternionicComputing.Semantics.RealGlobalSignEq.mem_unitary_iff
#print axioms QuaternionicComputing.Semantics.ComplexGlobalPhaseEq.mem_unitary_iff

#print axioms QuaternionicComputing.Semantics.RealInputBasisSignEq.basisMeasurementEq
#print axioms QuaternionicComputing.Semantics.ComplexInputBasisPhaseEq.basisMeasurementEq
#print axioms
  QuaternionicComputing.Semantics.RealOutputBasisSignEq.pureInputBasisMeasurementEq
#print axioms
  QuaternionicComputing.Semantics.ComplexOutputBasisPhaseEq.pureInputBasisMeasurementEq
#print axioms
  QuaternionicComputing.Semantics.RealProjectiveActionEq.pureInputBasisMeasurementEq
#print axioms
  QuaternionicComputing.Semantics.ComplexProjectiveActionEq.pureInputBasisMeasurementEq

#print axioms QuaternionicComputing.Semantics.ExactCircuitEq.realGlobalSignEq
#print axioms QuaternionicComputing.Semantics.ExactCircuitEq.complexGlobalPhaseEq
#print axioms QuaternionicComputing.Semantics.RealCircuitGlobalSignEq.append
#print axioms QuaternionicComputing.Semantics.ComplexCircuitGlobalPhaseEq.append
#print axioms QuaternionicComputing.Semantics.RealCircuitInputBasisSignEq.append_same_later
#print axioms
  QuaternionicComputing.Semantics.ComplexCircuitInputBasisPhaseEq.append_same_later
#print axioms QuaternionicComputing.Semantics.RealCircuitOutputBasisSignEq.prepend_same_earlier
#print axioms
  QuaternionicComputing.Semantics.ComplexCircuitOutputBasisPhaseEq.prepend_same_earlier
#print axioms QuaternionicComputing.Semantics.RealCircuitProjectiveActionEq.append_same_later
#print axioms
  QuaternionicComputing.Semantics.ComplexCircuitProjectiveActionEq.append_same_later
set_option linter.style.longLine false in
#print axioms QuaternionicComputing.Semantics.RealCircuitProjectiveActionEq.prepend_same_earlier_of_isLocallyUnitary
set_option linter.style.longLine false in
#print axioms QuaternionicComputing.Semantics.ComplexCircuitProjectiveActionEq.prepend_same_earlier_of_isLocallyUnitary

#print axioms QuaternionicComputing.Semantics.QuaternionCentralSignEq.equivalence
#print axioms QuaternionicComputing.Semantics.QuaternionInputRightPhaseEq.equivalence
#print axioms QuaternionicComputing.Semantics.QuaternionOutputLeftPhaseEq.equivalence
#print axioms QuaternionicComputing.Semantics.QuaternionProjectiveActionEq.equivalence
#print axioms
  QuaternionicComputing.Semantics.quaternionRawProjectiveActionEq_iff_projectiveActionEq
#print axioms QuaternionicComputing.Semantics.QuaternionCentralSignEq.mem_unitary_iff
#print axioms
  QuaternionicComputing.Semantics.QuaternionInputRightPhaseEq.basisMeasurementEq
#print axioms
  QuaternionicComputing.Semantics.QuaternionProjectiveActionEq.pureInputBasisMeasurementEq
#print axioms QuaternionicComputing.Semantics.ExactCircuitEq.quaternionCentralSignEq
set_option linter.style.longLine false in
#print axioms QuaternionicComputing.Semantics.QuaternionCircuitProjectiveActionEq.prepend_same_earlier_of_isLocallyUnitary
#print axioms
  QuaternionicComputing.Semantics.quaternionProjectiveActionEq_iff_centralSignEq_of_unitary
#print axioms
  QuaternionicComputing.Semantics.quaternionRankOneScalar_projectiveActionEq_iff_normSq_eq_one
#print axioms QuaternionicComputing.Semantics.quaternionRankOneJ_exception

#print axioms
  QuaternionicComputing.Semantics.BasisTransitionRelationEq.equivalence
#print axioms
  QuaternionicComputing.Semantics.BasisPermutationImplementation.permutation_unique
#print axioms
  QuaternionicComputing.Semantics.SameBasisBehavior.basisTransitionRelationEq
#print axioms QuaternionicComputing.Semantics.ExactOperatorEq.sameBasisBehavior
#print axioms QuaternionicComputing.Semantics.BasisMeasurementEq.sameBasisBehavior
#print axioms
  QuaternionicComputing.Semantics.SameBasisBehavior.quaternionInputRightPhaseEq
#print axioms
  QuaternionicComputing.Semantics.SameBasisBehavior.quaternionOutputLeftPhaseEq
#print axioms
  QuaternionicComputing.Semantics.sameBasisBehavior_iff_realBasisMeasurementEq
#print axioms
  QuaternionicComputing.Semantics.sameBasisBehavior_iff_complexBasisMeasurementEq
#print axioms
  QuaternionicComputing.Semantics.sameBasisBehavior_iff_quaternionBasisMeasurementEq
#print axioms
  QuaternionicComputing.Semantics.BasisClassicalUnitaryOperator.SameBasisBehavior.equivalence
#print axioms
  QuaternionicComputing.Semantics.RealBasisClassicalUnitaryOperator.ofPermMatrix

#print axioms QuaternionicComputing.Semantics.BasisClassicalCircuit.eval_mem_unitary
#print axioms QuaternionicComputing.Semantics.SameCircuitBasisBehavior.equivalence
#print axioms
  QuaternionicComputing.Semantics.SameCircuitBasisBehavior.iff_complexCircuitInputBasisPhaseEq
#print axioms
  QuaternionicComputing.Semantics.SameCircuitBasisBehavior.iff_quaternionCircuitInputRightPhaseEq
#print axioms
  QuaternionicComputing.Semantics.SameCircuitBasisBehavior.iff_quaternionCircuitOutputLeftPhaseEq
#print axioms
  QuaternionicComputing.Semantics.SameCircuitBasisBehavior.iff_quaternionBasisMeasurementEq
#print axioms
  QuaternionicComputing.Semantics.ExactCircuitEq.quaternionSameCircuitBasisBehavior
#print axioms
  QuaternionicComputing.Semantics.ComplexCircuitGlobalPhaseEq.sameCircuitBasisBehavior
#print axioms
  QuaternionicComputing.Semantics.QuaternionCircuitCentralSignEq.sameCircuitBasisBehavior
#print axioms QuaternionicComputing.Semantics.emptyBasisClassicalCircuit
#print axioms
  QuaternionicComputing.Semantics.basisPreparationCircuit_basisTransition
#print axioms QuaternionicComputing.Semantics.basisPreparationCircuit_eval_entry
#print axioms
  QuaternionicComputing.Semantics.basisPreparationCircuit_mulVec_ground

#print axioms
  QuaternionicComputing.Semantics.DensityMatrix.isEmpty_of_index_isEmpty
#print axioms QuaternionicComputing.Semantics.DensityMatrix.nonempty_iff
#print axioms QuaternionicComputing.Semantics.DensityMatrix.pure_apply
#print axioms QuaternionicComputing.Semantics.DensityMatrix.basis_apply
#print axioms
  QuaternionicComputing.Semantics.DensityMatrix.unitaryConjugate_posSemidef
#print axioms QuaternionicComputing.Semantics.DensityMatrix.unitaryConjugate_comp
#print axioms QuaternionicComputing.Semantics.DensityMatrix.unitaryConjugate_pure
#print axioms QuaternionicComputing.Semantics.RealDensityMatrix.ofState_apply
#print axioms QuaternionicComputing.Semantics.ComplexDensityMatrix.ofState_apply

#print axioms QuaternionicComputing.Semantics.Effect.complement_posSemidef
#print axioms QuaternionicComputing.Semantics.Effect.rankOneProjector_le_one
#print axioms QuaternionicComputing.Semantics.Effect.projector_coe
#print axioms QuaternionicComputing.Semantics.Effect.basis_coe_eq_density_basis
#print axioms
  QuaternionicComputing.Semantics.Effect.trace_mul_nonneg_of_posSemidef
#print axioms QuaternionicComputing.Semantics.Effect.bornScalar_im_eq_zero
#print axioms QuaternionicComputing.Semantics.Effect.bornValue_mem_Icc
#print axioms QuaternionicComputing.Semantics.Effect.bornValue_complement
#print axioms QuaternionicComputing.Semantics.Effect.bornValue_basis_pure
#print axioms QuaternionicComputing.Semantics.Effect.bornValue_basis_basis

#print axioms
  QuaternionicComputing.Semantics.Effect.trace_rankOneProjector_mul_eq_inner
#print axioms QuaternionicComputing.Semantics.quadratic_eq_of_unit_sphere
#print axioms
  QuaternionicComputing.Semantics.posSemidef_eq_of_forall_effect_trace_re_eq
#print axioms
  QuaternionicComputing.Semantics.DensityMatrix.eq_iff_forall_effect_bornValue_eq
#print axioms
  QuaternionicComputing.Semantics.DensityMatrix.eq_of_forall_effect_bornValue_eq

#print axioms QuaternionicComputing.Semantics.UnitaryOperator.identity_evolve
#print axioms QuaternionicComputing.Semantics.UnitaryOperator.followedBy_evolve
#print axioms QuaternionicComputing.Semantics.ChannelEq.equivalence
#print axioms QuaternionicComputing.Semantics.ChannelEq.followedBy
#print axioms QuaternionicComputing.Semantics.AllMeasurementEq.equivalence
#print axioms QuaternionicComputing.Semantics.AllMeasurementEq.channelEq
#print axioms
  QuaternionicComputing.Semantics.channelEq_iff_allMeasurementEq

#print axioms
  QuaternionicComputing.Semantics.realSignEquivalent_of_normalized_pureMatrix_eq
#print axioms
  QuaternionicComputing.Semantics.complexRightPhaseEquivalent_of_normalized_pureMatrix_eq
#print axioms
  QuaternionicComputing.Semantics.RealRawProjectiveActionEq.equivalence
#print axioms
  QuaternionicComputing.Semantics.ComplexRawProjectiveActionEq.equivalence
#print axioms
  QuaternionicComputing.Semantics.realRawProjectiveActionEq_iff_projectiveActionEq
#print axioms
  QuaternionicComputing.Semantics.complexRawProjectiveActionEq_iff_projectiveActionEq
#print axioms
  QuaternionicComputing.Semantics.RealRawProjectiveActionEq.globalSignEq_of_unitary
#print axioms
  QuaternionicComputing.Semantics.ComplexRawProjectiveActionEq.globalPhaseEq_of_unitary
#print axioms QuaternionicComputing.Semantics.RealGlobalSignEq.channelEq
#print axioms QuaternionicComputing.Semantics.ComplexGlobalPhaseEq.channelEq
#print axioms
  QuaternionicComputing.Semantics.ChannelEq.realProjectiveActionEq
#print axioms
  QuaternionicComputing.Semantics.ChannelEq.complexProjectiveActionEq
#print axioms
  QuaternionicComputing.Semantics.realGlobalSignEq_iff_channelEq
#print axioms
  QuaternionicComputing.Semantics.complexGlobalPhaseEq_iff_channelEq
#print axioms
  QuaternionicComputing.Semantics.realProjectiveActionEq_iff_channelEq
#print axioms
  QuaternionicComputing.Semantics.complexProjectiveActionEq_iff_channelEq
#print axioms QuaternionicComputing.Semantics.realGlobalSignEq_of_isEmpty
#print axioms QuaternionicComputing.Semantics.complexGlobalPhaseEq_of_isEmpty

#print axioms QuaternionicComputing.Semantics.UnitaryCircuit.toOperator_append
#print axioms QuaternionicComputing.Semantics.CircuitChannelEq.equivalence
#print axioms QuaternionicComputing.Semantics.CircuitChannelEq.append
#print axioms
  QuaternionicComputing.Semantics.CircuitAllMeasurementEq.equivalence
#print axioms
  QuaternionicComputing.Semantics.circuitChannelEq_iff_allMeasurementEq
#print axioms QuaternionicComputing.Semantics.ExactCircuitEq.circuitChannelEq
#print axioms
  QuaternionicComputing.Semantics.RealCircuitGlobalSignEq.circuitChannelEq
#print axioms
  QuaternionicComputing.Semantics.ComplexCircuitGlobalPhaseEq.circuitChannelEq
#print axioms
  QuaternionicComputing.Semantics.CircuitChannelEq.realGlobalSignEq
#print axioms
  QuaternionicComputing.Semantics.CircuitChannelEq.complexGlobalPhaseEq
#print axioms
  QuaternionicComputing.Semantics.realCircuitGlobalSignEq_iff_channelEq
#print axioms
  QuaternionicComputing.Semantics.complexCircuitGlobalPhaseEq_iff_channelEq
#print axioms
  QuaternionicComputing.Semantics.realCircuitProjectiveActionEq_iff_channelEq
#print axioms
  QuaternionicComputing.Semantics.complexCircuitProjectiveActionEq_iff_channelEq

#print axioms
  QuaternionicComputing.Semantics.PureInputBasisMeasurementEq.realBasisMeasurementEq
#print axioms
  QuaternionicComputing.Semantics.PureInputBasisMeasurementEq.complexBasisMeasurementEq
#print axioms
  QuaternionicComputing.Semantics.PureInputBasisMeasurementEq.quaternionBasisMeasurementEq
#print axioms
  QuaternionicComputing.Semantics.PureInputBasisMeasurementEq.realOutputBasisSignEq
#print axioms
  QuaternionicComputing.Semantics.PureInputBasisMeasurementEq.complexOutputBasisPhaseEq
#print axioms
  QuaternionicComputing.Semantics.PureInputBasisMeasurementEq.quaternionOutputLeftPhaseEq
#print axioms
  QuaternionicComputing.Semantics.realOutputBasisSignEq_iff_pureInputBasisMeasurementEq
#print axioms
  QuaternionicComputing.Semantics.complexOutputBasisPhaseEq_iff_pureInputBasisMeasurementEq
#print axioms
  QuaternionicComputing.Semantics.quaternionOutputLeftPhaseEq_iff_pureInputBasisMeasurementEq

#print axioms
  QuaternionicComputing.State.FiniteDistribution.eq_iff_singletonEventWeight_eq
#print axioms
  QuaternionicComputing.State.FiniteDistribution.eq_iff_eventWeight_eq
#print axioms
  QuaternionicComputing.State.FiniteDistribution.eq_iff_allPushforward_eq_sameUniverse
#print axioms
  QuaternionicComputing.Semantics.normalizedDistributionEq_iff_eventWeight_eq
#print axioms
  QuaternionicComputing.Semantics.basisWeightEq_iff_allPushforward_eq_sameUniverse
#print axioms QuaternionicComputing.Semantics.ExactStateEq.complexRay_mk_eq
#print axioms QuaternionicComputing.Semantics.ExactStateEq.quaternionRay_mk_eq
#print axioms
  QuaternionicComputing.Semantics.ComplexStatePhaseEq.basisWeightEq_of_complexRay_mk_eq

#print axioms
  QuaternionicComputing.Semantics.realGlobalSignEq_iff_projectiveActionEq
#print axioms
  QuaternionicComputing.Semantics.complexGlobalPhaseEq_iff_projectiveActionEq
#print axioms
  QuaternionicComputing.Semantics.ChannelEq.realPureInputBasisMeasurementEq
#print axioms
  QuaternionicComputing.Semantics.ChannelEq.complexOutputBasisPhaseEq
#print axioms
  QuaternionicComputing.Semantics.AllMeasurementEq.complexBasisMeasurementEq
#print axioms
  QuaternionicComputing.Semantics.realCircuitOutputBasisSignEq_iff_pureInputBasisMeasurementEq
#print axioms
  QuaternionicComputing.Semantics.complexCircuitOutputBasisPhaseEq_iff_pureInputBasisMeasurementEq
#print axioms
  QuaternionicComputing.Semantics.quaternionCircuitOutputLeftPhaseEq_iff_pureInputBasisMeasurementEq
#print axioms
  QuaternionicComputing.Semantics.realCircuitGlobalSignEq_iff_projectiveActionEq
#print axioms
  QuaternionicComputing.Semantics.complexCircuitGlobalPhaseEq_iff_projectiveActionEq
#print axioms
  QuaternionicComputing.Semantics.CircuitChannelEq.complexOutputBasisPhaseEq
#print axioms
  QuaternionicComputing.Semantics.CircuitAllMeasurementEq.realPureInputBasisMeasurementEq

#print axioms QuaternionicComputing.Semantics.ExactStateEncoding.comp
#print axioms QuaternionicComputing.Semantics.LosslessStateEncoding.comp
#print axioms QuaternionicComputing.Semantics.ExactOperatorEmbedding.comp
#print axioms QuaternionicComputing.Semantics.StateIntertwining.comp
#print axioms QuaternionicComputing.Semantics.AllTopStateIntertwining.forTop
#print axioms QuaternionicComputing.Semantics.DecodedBasisWeightAgreement.comp
#print axioms QuaternionicComputing.Semantics.DecodedDistributionAgreement.comp
#print axioms
  QuaternionicComputing.Semantics.DecodedDistributionAgreement.eventWeight_eq
#print axioms
  QuaternionicComputing.Semantics.AllTopDecodedBasisWeightAgreement.forTopInput
#print axioms
  QuaternionicComputing.Semantics.AllTopDecodedDistributionAgreement.forTopInput

#print axioms QuaternionicComputing.Semantics.realColumn0_exactStateEncoding
#print axioms QuaternionicComputing.Semantics.realColumn0_losslessStateEncoding
#print axioms QuaternionicComputing.Semantics.realColumn0_rightInverse
#print axioms QuaternionicComputing.Semantics.realColumn0LinearEquiv
#print axioms QuaternionicComputing.Semantics.realColumn0StateEquiv
#print axioms QuaternionicComputing.Semantics.complexColumn0_exactStateEncoding
#print axioms QuaternionicComputing.Semantics.complexColumn0_losslessStateEncoding
#print axioms QuaternionicComputing.Semantics.complexColumn0_rightInverse
#print axioms QuaternionicComputing.Semantics.complexColumn0LinearEquiv
#print axioms QuaternionicComputing.Semantics.complexColumn0StateEquiv

#print axioms
  QuaternionicComputing.Semantics.realifyMatrix_allCoefficient_stateIntertwining
#print axioms
  QuaternionicComputing.Semantics.complexifyMatrix_allCoefficient_stateIntertwining
#print axioms QuaternionicComputing.Semantics.directRealify_exactOperatorEmbedding
#print axioms
  QuaternionicComputing.Semantics.realifyPlacedGate_exactOperatorEmbedding
#print axioms
  QuaternionicComputing.Semantics.complexifyPlacedGate_exactOperatorEmbedding
#print axioms QuaternionicComputing.Semantics.realifyCircuit_exactOperatorEmbedding
#print axioms
  QuaternionicComputing.Semantics.complexifyCircuit_exactOperatorEmbedding
#print axioms
  QuaternionicComputing.Semantics.realifyCircuit_allCoefficient_stateIntertwining
#print axioms
  QuaternionicComputing.Semantics.complexifyCircuit_allCoefficient_stateIntertwining
#print axioms
  QuaternionicComputing.Semantics.scheduledComplexifyCircuit_exactOperatorEmbedding
#print axioms
  QuaternionicComputing.Semantics.scheduledComplexifyCircuit_allCoefficient_stateIntertwining
#print axioms
  QuaternionicComputing.Semantics.scheduledComplexifyCircuit_eval_ne_of_source_ne
#print axioms
  QuaternionicComputing.Semantics.quaternionToRealCircuit_exactOperatorEmbedding
#print axioms
  QuaternionicComputing.Semantics.quaternionToRealCircuit_allCoefficient_stateIntertwining
#print axioms
  QuaternionicComputing.Semantics.compileRealifyCircuit_exactOperatorEmbedding
#print axioms
  QuaternionicComputing.Semantics.compileComplexifyCircuit_exactOperatorEmbedding

#print axioms QuaternionicComputing.Simulation.sumSectorWeightDecoder
#print axioms QuaternionicComputing.Simulation.addedWireWeightDecoder
#print axioms QuaternionicComputing.Simulation.addedWireDistributionDecoder
#print axioms
  QuaternionicComputing.Simulation.addedWireDistributionDecoder_weight
#print axioms
  QuaternionicComputing.Simulation.addedWireDistributionDecoder_compat
#print axioms
  QuaternionicComputing.Simulation.addedWireDistributionDecoder_eq_pushforward
#print axioms QuaternionicComputing.Simulation.twoAddedWireWeightDecoder
#print axioms QuaternionicComputing.Simulation.twoAddedWireDistributionDecoder
#print axioms
  QuaternionicComputing.Simulation.twoAddedWireDistributionDecoder_weight
#print axioms
  QuaternionicComputing.Simulation.twoAddedWireDistributionDecoder_compat

#print axioms
  QuaternionicComputing.Simulation.addedWireDistributionDecoder_ofNormalizedState
#print axioms
  QuaternionicComputing.Simulation.realifyCircuitFullOutputDistribution
#print axioms
  QuaternionicComputing.Simulation.complexifyCircuitFullOutputDistribution
#print axioms
  QuaternionicComputing.Simulation.quaternionToRealCircuitFullOutputDistribution
#print axioms
  QuaternionicComputing.Simulation.quaternionToRealCircuitBottomDistribution
#print axioms
  QuaternionicComputing.Simulation.quaternionToRealCircuitBottomDistribution_eq
#print axioms
  QuaternionicComputing.Simulation.quaternionToRealCircuitOutput_eventWeight
#print axioms
  QuaternionicComputing.Simulation.quaternionToRealCircuitOutput_pushforward_eq

#print axioms
  QuaternionicComputing.Semantics.realTopCombination_allRebit_raw_decodedBasisWeightAgreement
#print axioms
  QuaternionicComputing.Semantics.complexTopCombination_allQubit_raw_decodedBasisWeightAgreement
#print axioms
  QuaternionicComputing.Semantics.realifyCircuit_allRebit_raw_decodedBasisWeightAgreement
#print axioms
  QuaternionicComputing.Semantics.realifyCircuit_allRebit_decodedDistributionAgreement
#print axioms
  QuaternionicComputing.Semantics.realifyCircuit_decodedEventWeight_eq
#print axioms
  QuaternionicComputing.Semantics.realifyCircuit_decodedPushforward_eq
#print axioms
  QuaternionicComputing.Semantics.complexifyCircuit_allQubit_raw_decodedBasisWeightAgreement
#print axioms
  QuaternionicComputing.Semantics.complexifyCircuit_allQubit_decodedDistributionAgreement
#print axioms
  QuaternionicComputing.Semantics.complexifyCircuit_decodedEventWeight_eq
#print axioms
  QuaternionicComputing.Semantics.complexifyCircuit_decodedPushforward_eq
#print axioms
QuaternionicComputing.Semantics.scheduledComplexifyCircuit_allQubit_raw_decodedBasisWeightAgreement
#print axioms
  QuaternionicComputing.Semantics.scheduledComplexifyCircuit_allQubit_decodedDistributionAgreement
#print axioms
  QuaternionicComputing.Semantics.scheduledComplexifyCircuit_decodedEventWeight_eq
#print axioms
  QuaternionicComputing.Semantics.scheduledComplexifyCircuit_decodedPushforward_eq
#print axioms
  QuaternionicComputing.Semantics.quaternionToRealCircuit_allPureTop_raw_decodedBasisWeightAgreement
#print axioms
  QuaternionicComputing.Semantics.quaternionToRealCircuit_allPureTop_decodedDistributionAgreement
#print axioms
  QuaternionicComputing.Semantics.quaternionToRealCircuit_decodedEventWeight_eq
#print axioms
  QuaternionicComputing.Semantics.quaternionToRealCircuit_decodedPushforward_eq

#print axioms QuaternionicComputing.Simulation.depth_realifyCircuit_eq_gateCount
#print axioms QuaternionicComputing.Simulation.depth_complexifyCircuit_eq_gateCount
#print axioms QuaternionicComputing.Simulation.depth_quaternionToRealCircuit_eq_gateCount
#print axioms QuaternionicComputing.Simulation.totalDenseEntrySlots_realifyCircuit
#print axioms QuaternionicComputing.Simulation.totalDenseEntrySlots_complexifyCircuit
#print axioms QuaternionicComputing.Simulation.totalDenseEntrySlots_quaternionToRealCircuit

#print axioms QuaternionicComputing.Simulation.eval_compile_realifyCircuit
#print axioms QuaternionicComputing.Simulation.gateCount_compile_realifyCircuit_le
#print axioms QuaternionicComputing.Simulation.depth_compileRealifyCircuitSerialLayering_le
#print axioms QuaternionicComputing.Simulation.eval_compile_complexifyCircuit
#print axioms QuaternionicComputing.Simulation.gateCount_compile_complexifyCircuit_le
#print axioms QuaternionicComputing.Simulation.depth_compileComplexifyCircuitSerialLayering_le

#print axioms QuaternionicComputing.Simulation.realifyCircuitBottomDistribution_eq
#print axioms QuaternionicComputing.Simulation.realifyCircuitOutput_eventWeight
#print axioms QuaternionicComputing.Simulation.realifyCircuitOutput_pushforward_eq
#print axioms QuaternionicComputing.Simulation.complexifyCircuitBottomDistribution_eq
#print axioms QuaternionicComputing.Simulation.complexifyCircuitOutput_eventWeight
#print axioms QuaternionicComputing.Simulation.complexifyCircuitOutput_pushforward_eq

#print axioms QuaternionicComputing.Quaternion.card_directRealIndex
#print axioms QuaternionicComputing.Quaternion.directRealify_eq_reindex
#print axioms QuaternionicComputing.Quaternion.directRealify_mul
#print axioms QuaternionicComputing.Quaternion.directRealify_conjTranspose
#print axioms QuaternionicComputing.Quaternion.directRealify_injective
#print axioms QuaternionicComputing.Quaternion.directRealify_mem_specialOrthogonal
#print axioms QuaternionicComputing.Quaternion.directRealifyUnitaryEquivImage

#print axioms
  QuaternionicComputing.Matrix.ProperImage.realWitness_specialOrthogonal_not_realify
#print axioms
  QuaternionicComputing.Matrix.ProperImage.complexWitness_specialUnitary_not_complexify
#print axioms
  QuaternionicComputing.Matrix.ProperImage.directWitness_specialOrthogonal_not_directRealify

#print axioms QuaternionicComputing.Complex.rightPhaseEquivalent_equivalence
#print axioms QuaternionicComputing.State.rightPhaseEquivalent_complexBasisWeight
#print axioms QuaternionicComputing.State.rightPhaseEquivalent_complexTotalWeight
#print axioms QuaternionicComputing.State.rightPhaseEquivalent_complex_mulVec

#print axioms QuaternionicComputing.Circuit.basisPreparationMatrix_mem_unitary
#print axioms QuaternionicComputing.Circuit.basisPreparationGate_mulVec_ground
#print axioms
  QuaternionicComputing.Circuit.eval_prepend_basisPreparation_mulVec_ground

#print axioms
  QuaternionicComputing.Circuit.ProductInputOrderingWitness.groundColumn_product
#print axioms
  QuaternionicComputing.Circuit.ProductInputOrderingWitness.ground_outputs_not_rightPhaseEquivalent
#print axioms
  QuaternionicComputing.Circuit.ProductInputOrderingWitness.ground_outputs_basis_weights_eq

#print axioms
  QuaternionicComputing.Simulation.NonProductWitness.sourceColumn_normalization
#print axioms
  QuaternionicComputing.Simulation.NonProductWitness.encodedState_not_pureTopBottomProduct

/-! ## Goal 2 Stage 10: metric approximation boundary -/

#print axioms
  QuaternionicComputing.Semantics.operatorDistance_eq_continuousLinearMapNorm
#print axioms
  QuaternionicComputing.Semantics.operatorClose_zero_iff_exactOperatorEq
#print axioms QuaternionicComputing.Semantics.OperatorClose.additive_trans
#print axioms QuaternionicComputing.Semantics.OperatorClose.mul_of_unitary
#print axioms QuaternionicComputing.Semantics.operatorDistance_mulVec_le
#print axioms
  QuaternionicComputing.Semantics.mappedOperatorClose_zero_iff_exactOperatorEmbedding

#print axioms
  QuaternionicComputing.Semantics.operatorDistance_smul_of_norm_eq_one
#print axioms QuaternionicComputing.Semantics.realGlobalSignClose_zero_iff
#print axioms QuaternionicComputing.Semantics.RealGlobalSignClose.additive_trans
#print axioms QuaternionicComputing.Semantics.complexGlobalPhaseClose_zero_iff
#print axioms
  QuaternionicComputing.Semantics.ComplexGlobalPhaseClose.additive_trans

#print axioms QuaternionicComputing.Semantics.quaternionMulVecCLM_mul
#print axioms
  QuaternionicComputing.Semantics.quaternionOperatorNorm_eq_zero_iff
#print axioms QuaternionicComputing.Semantics.quaternionOperatorDistance_mul
#print axioms
  QuaternionicComputing.Semantics.quaternionOperatorDistance_mulVec
#print axioms
  QuaternionicComputing.Semantics.QuaternionOperatorClose.zero_iff_exactOperatorEq
#print axioms
  QuaternionicComputing.Semantics.QuaternionCentralSignClose.additive_trans
#print axioms
  QuaternionicComputing.Semantics.QuaternionCentralSignClose.zero_iff_quaternionCentralSignEq
#print axioms
  QuaternionicComputing.Semantics.quaternionOperatorNorm_eq_l2_opNorm_complexify

#print axioms QuaternionicComputing.Semantics.columnL2Distance_eq_zero_iff
#print axioms QuaternionicComputing.Semantics.ColumnClose.additive_trans
#print axioms QuaternionicComputing.Semantics.columnL2Distance_right_mul
#print axioms
  QuaternionicComputing.Semantics.RightUnitPhaseColumnClose.additive_trans
#print axioms
  QuaternionicComputing.Semantics.realStateRayClose_zero_iff_realStatePhaseEq
#print axioms
  QuaternionicComputing.Semantics.complexStateRayClose_zero_iff_complexStatePhaseEq
#print axioms
  QuaternionicComputing.Semantics.quaternionStateRayClose_zero_iff_quaternionStatePhaseEq
#print axioms QuaternionicComputing.Semantics.realState_l2Norm_eq_one
#print axioms
  QuaternionicComputing.Semantics.operatorDistance_realState_output_le
#print axioms
  QuaternionicComputing.Semantics.operatorDistance_complexState_output_le
#print axioms
  QuaternionicComputing.Semantics.quaternionOperatorDistance_quaternionState_output_le

#print axioms
  QuaternionicComputing.Semantics.totalVariationDistance_eq_zero_iff
#print axioms QuaternionicComputing.Semantics.totalVariationDistance_triangle
#print axioms QuaternionicComputing.Semantics.DistributionClose.additive_trans
#print axioms QuaternionicComputing.Semantics.totalVariationDistance_le_one
#print axioms
  QuaternionicComputing.Semantics.abs_eventWeight_sub_le_totalVariationDistance
#print axioms
  QuaternionicComputing.Semantics.totalVariationDistance_pushforward_le

namespace QuaternionicComputing.Semantics.ApproximationStrictness

#print axioms complexScalarPhaseChain_unitary
#print axioms operatorClose_one_not_transitive
#print axioms complexScalarPhaseChain_distances
#print axioms operatorClose_sqrtTwo_not_transitive_on_complex_unitaries
#print axioms rawDistance_one_negOne_eq_two_and_complexGlobalPhaseClose_zero
#print axioms distributionClose_half_not_transitive

end QuaternionicComputing.Semantics.ApproximationStrictness

/-! ## Goal 2 Stage 11: strongest classifications of existing results -/

#print axioms
  QuaternionicComputing.Semantics.normalizedQuaternionLeftPhase_rejection
#print axioms
  QuaternionicComputing.Semantics.realCanonicalColumns_reducedOuterAgreement
#print axioms
  QuaternionicComputing.Semantics.quaternionGroundOutputs_distributionEq_not_rayEq
#print axioms
  QuaternionicComputing.Semantics.scheduledCircuit_exactCircuitEq_of_pairwise_commute
#print axioms
  QuaternionicComputing.Semantics.quaternionOrderingWitness_scopeBoundary
#print axioms
  QuaternionicComputing.Circuit.ExactGateCompiler.compileCircuit_exactCircuitEq

/-! ## Goal 2 Stage 12: projective action determines input-column phase -/

#print axioms
  QuaternionicComputing.Semantics.RealRawProjectiveActionEq.inputBasisSignEq
#print axioms
  QuaternionicComputing.Semantics.ComplexRawProjectiveActionEq.inputBasisPhaseEq
#print axioms
  QuaternionicComputing.Semantics.QuaternionRawProjectiveActionEq.inputRightPhaseEq
#print axioms
  QuaternionicComputing.Semantics.RealProjectiveActionEq.inputBasisSignEq
#print axioms
  QuaternionicComputing.Semantics.ComplexProjectiveActionEq.inputBasisPhaseEq
#print axioms
  QuaternionicComputing.Semantics.QuaternionProjectiveActionEq.inputRightPhaseEq
#print axioms
  QuaternionicComputing.Semantics.RealCircuitProjectiveActionEq.inputBasisSignEq
#print axioms
  QuaternionicComputing.Semantics.ComplexCircuitProjectiveActionEq.inputBasisPhaseEq
#print axioms
  QuaternionicComputing.Semantics.QuaternionCircuitProjectiveActionEq.inputRightPhaseEq
