module

public import QuaternionicComputing

/-!
# Axiom audit

This module grows with the public theorem surface.  Building it prints the
axioms used by each main exported result.
-/

#print axioms QuaternionicComputing.Quaternion.eq_complexPart_add_jPart_mul_j
#print axioms QuaternionicComputing.Quaternion.components_injective
#print axioms QuaternionicComputing.Quaternion.complexPart_mul
#print axioms QuaternionicComputing.Quaternion.jPart_mul
#print axioms QuaternionicComputing.Quaternion.complexPart_star
#print axioms QuaternionicComputing.Quaternion.jPart_star
#print axioms QuaternionicComputing.Quaternion.normSq_eq_complexPart_add_jPart
#print axioms QuaternionicComputing.Quaternion.phaseWitnessGate_normSq
#print axioms QuaternionicComputing.Quaternion.not_leftPhaseEquivalent_gate_i_input
#print axioms QuaternionicComputing.Quaternion.rightPhaseEquivalent_gate

#print axioms QuaternionicComputing.Matrix.realify_injective
#print axioms QuaternionicComputing.Matrix.realify_mul
#print axioms QuaternionicComputing.Matrix.realify_conjTranspose
#print axioms QuaternionicComputing.Matrix.realify_mulVec
#print axioms QuaternionicComputing.Matrix.realify_map_ofReal
#print axioms QuaternionicComputing.Matrix.realifyUnitaryEquivImage
#print axioms QuaternionicComputing.Matrix.realify_mem_orthogonal
#print axioms QuaternionicComputing.Matrix.realify_det
#print axioms QuaternionicComputing.Matrix.realify_mem_specialOrthogonal

#print axioms QuaternionicComputing.Quaternion.complexify_injective
#print axioms QuaternionicComputing.Quaternion.complexify_mul
#print axioms QuaternionicComputing.Quaternion.complexify_conjTranspose
#print axioms QuaternionicComputing.Quaternion.complexify_mul_complexificationJ
#print axioms QuaternionicComputing.Quaternion.complexifyUnitaryEquivImage
#print axioms QuaternionicComputing.Quaternion.complexify_mem_unitary
#print axioms QuaternionicComputing.Quaternion.complexify_mem_symplectic
#print axioms QuaternionicComputing.Quaternion.complexify_det_star_fixed
#print axioms QuaternionicComputing.Quaternion.complexify_det_eq_one_or_neg_one_of_mem_unitary

#print axioms QuaternionicComputing.State.Quaterbit.normalization
#print axioms QuaternionicComputing.State.quaternionBasisWeight_right_smul_of_normSq_eq_one
#print axioms QuaternionicComputing.State.QuaternionState.rightPhaseEquivalent_rightPhase
#print axioms QuaternionicComputing.State.rightPhaseEquivalent_quaternionBasisWeight
#print axioms QuaternionicComputing.State.quaternion_mulVec_right_smul
#print axioms QuaternionicComputing.State.rightPhaseEquivalent_mulVec

#print axioms QuaternionicComputing.State.realColumn0_injective
#print axioms QuaternionicComputing.State.realColumn1_injective
#print axioms QuaternionicComputing.State.realify_mulVec_realColumn0
#print axioms QuaternionicComputing.State.realify_mulVec_realColumn1
#print axioms QuaternionicComputing.State.realColumns_orthogonal
#print axioms QuaternionicComputing.State.realColumn0_bottomWeight
#print axioms QuaternionicComputing.State.realTopCombination_bottomWeight_of_rebit
#print axioms QuaternionicComputing.State.reducedRealOuter_realColumns
#print axioms QuaternionicComputing.State.reducedRealOuter_diagonal

#print axioms QuaternionicComputing.State.complexColumn0_injective
#print axioms QuaternionicComputing.State.complexColumn1_injective
#print axioms QuaternionicComputing.State.complexify_mulVec_complexColumn0
#print axioms QuaternionicComputing.State.complexify_mulVec_complexColumn1
#print axioms QuaternionicComputing.State.complexColumns_orthogonal
#print axioms QuaternionicComputing.State.complexColumn0_bottomWeight
#print axioms QuaternionicComputing.State.complexColumn1_bottomWeight
#print axioms QuaternionicComputing.State.complexTopCombination_bottomWeight_of_qubit

#print axioms QuaternionicComputing.Circuit.kronecker_one_mul
#print axioms QuaternionicComputing.Circuit.place_mul
#print axioms QuaternionicComputing.Circuit.place_mem_unitary
#print axioms QuaternionicComputing.Circuit.supportSplit
#print axioms QuaternionicComputing.Circuit.PlacedGate.denote_mem_unitary
#print axioms QuaternionicComputing.Circuit.OrderedCircuit.eval_append
#print axioms QuaternionicComputing.Circuit.OrderedCircuit.eval_map_of_denote_eq
#print axioms QuaternionicComputing.Circuit.OrderedCircuit.eval_mem_unitary
#print axioms QuaternionicComputing.Circuit.OrderSanity.eval_i_then_j_entry
#print axioms QuaternionicComputing.Circuit.OrderSanity.eval_j_then_i_entry

#print axioms QuaternionicComputing.Circuit.wireRealify_place
#print axioms QuaternionicComputing.Circuit.realifyPlacedGate_denote
#print axioms QuaternionicComputing.Circuit.localArity_realifyPlacedGate
#print axioms QuaternionicComputing.Circuit.isLocallyUnitary_realifyPlacedGate

#print axioms QuaternionicComputing.Circuit.wireComplexify_place
#print axioms QuaternionicComputing.Circuit.complexifyPlacedGate_denote
#print axioms QuaternionicComputing.Circuit.localArity_complexifyPlacedGate
#print axioms QuaternionicComputing.Circuit.isLocallyUnitary_complexifyPlacedGate

#print axioms QuaternionicComputing.State.star_dotProduct_mulVec_of_mem_unitary
#print axioms QuaternionicComputing.State.complexTotalWeight_mulVec_of_mem_unitary
#print axioms QuaternionicComputing.State.quaternionTotalWeight_mulVec_of_mem_unitary
#print axioms QuaternionicComputing.State.RealState.evolveUnitary
#print axioms QuaternionicComputing.State.ComplexState.evolveUnitary
#print axioms QuaternionicComputing.State.QuaternionState.evolveUnitary

#print axioms QuaternionicComputing.Circuit.card_addedWire
#print axioms QuaternionicComputing.Circuit.OrderedCircuit.maxLocalArity_le_iff
#print axioms QuaternionicComputing.Circuit.OrderedCircuit.mem_map_arity_provenance
#print axioms QuaternionicComputing.Circuit.OrderedCircuit.maxLocalArity_map_eq_add_one_of_nonempty

#print axioms QuaternionicComputing.Simulation.reindex_mulVec_transportAddedColumn
#print axioms QuaternionicComputing.Simulation.totalWeight_transportAddedColumn
#print axioms QuaternionicComputing.Simulation.sum_addedWireBottomWeight
#print axioms QuaternionicComputing.Simulation.sum_addedWireBottomWeight_normalized

#print axioms QuaternionicComputing.Simulation.eval_realifyCircuit
#print axioms QuaternionicComputing.Simulation.mem_realifyCircuit_arity
#print axioms QuaternionicComputing.Simulation.maxLocalArity_realifyCircuit_of_nonempty
#print axioms QuaternionicComputing.Simulation.eval_realifyCircuit_mulVec_wireRealTopCombination
#print axioms QuaternionicComputing.Simulation.realifyCircuitOutput_bottomProbability
#print axioms QuaternionicComputing.Simulation.complexToReal_exactSimulation

#print axioms QuaternionicComputing.Simulation.eval_complexifyCircuit
#print axioms QuaternionicComputing.Simulation.mem_complexifyCircuit_arity
#print axioms QuaternionicComputing.Simulation.maxLocalArity_complexifyCircuit_of_nonempty
#print axioms
  QuaternionicComputing.Simulation.eval_complexifyCircuit_mulVec_wireComplexTopCombination
#print axioms QuaternionicComputing.Simulation.complexifyCircuitOutput_bottomProbability
#print axioms QuaternionicComputing.Simulation.quaternionToComplex_exactSimulation

#print axioms QuaternionicComputing.Simulation.eval_quaternionToRealCircuit
#print axioms QuaternionicComputing.Simulation.mem_quaternionToRealCircuit_arity
#print axioms QuaternionicComputing.Simulation.quaternionToRealCircuitOutput_nestedEncoding_apply
#print axioms QuaternionicComputing.Simulation.quaternionToRealCircuitOutput_bottomProbability
#print axioms QuaternionicComputing.Simulation.quaternionToReal_exactSimulation

#print axioms QuaternionicComputing.Simulation.Examples.realifyComplexICircuit_true_amplitude
#print axioms QuaternionicComputing.Simulation.Examples.complexifyQuaternionJCircuit_true_amplitude
