module

public import QuaternionicComputing

/-!
# Axiom audit

This module grows with the public theorem surface.  Building it prints the
axioms used by each main exported result.
-/

#print axioms QuaternionicComputing.Quaternion.eq_complexPart_add_jPart_mul_j
#print axioms QuaternionicComputing.Quaternion.components_injective
#print axioms QuaternionicComputing.Quaternion.complexPart_mul
#print axioms QuaternionicComputing.Quaternion.jPart_mul
#print axioms QuaternionicComputing.Quaternion.complexPart_star
#print axioms QuaternionicComputing.Quaternion.jPart_star
#print axioms QuaternionicComputing.Quaternion.normSq_eq_complexPart_add_jPart
#print axioms QuaternionicComputing.Quaternion.phaseWitnessGate_normSq
#print axioms QuaternionicComputing.Quaternion.not_leftPhaseEquivalent_gate_i_input
#print axioms QuaternionicComputing.Quaternion.rightPhaseEquivalent_gate

#print axioms QuaternionicComputing.Matrix.realify_injective
#print axioms QuaternionicComputing.Matrix.realify_mul
#print axioms QuaternionicComputing.Matrix.realify_conjTranspose
#print axioms QuaternionicComputing.Matrix.realify_mulVec
#print axioms QuaternionicComputing.Matrix.realify_map_ofReal
#print axioms QuaternionicComputing.Matrix.realifyUnitaryEquivImage
#print axioms QuaternionicComputing.Matrix.realify_mem_orthogonal
#print axioms QuaternionicComputing.Matrix.realify_det
#print axioms QuaternionicComputing.Matrix.realify_mem_specialOrthogonal

#print axioms QuaternionicComputing.Quaternion.complexify_injective
#print axioms QuaternionicComputing.Quaternion.complexify_mul
#print axioms QuaternionicComputing.Quaternion.complexify_conjTranspose
#print axioms QuaternionicComputing.Quaternion.complexify_mul_complexificationJ
#print axioms QuaternionicComputing.Quaternion.complexifyUnitaryEquivImage
#print axioms QuaternionicComputing.Quaternion.complexify_mem_unitary
#print axioms QuaternionicComputing.Quaternion.complexify_mem_symplectic
#print axioms QuaternionicComputing.Quaternion.complexify_det_star_fixed
#print axioms QuaternionicComputing.Quaternion.complexify_det_eq_one_or_neg_one_of_mem_unitary
